name: deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with Maven
        working-directory: ./EnglishMessenger
        run: ./mvnw clean package -DskipTests
  prepare-environment:
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Stop and remove containers
        run: docker compose $GITHUB_WORKSPACE/Messenger/docker-compose.yml down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build docker
        run: docker compose $GITHUB_WORKSPACE/Messenger/docker-compose.yml build
      - name: Up docker
        run: docker compose $GITHUB_WORKSPACE/Messenger/docker-compose.yml up
